services:
  - type: web
    name: autosoc
    runtime: node
    plan: free
    region: oregon
    buildCommand: |
      cd frontend && npm install --include=dev && npm run build && cd ../backend && npm install --include=dev && npm run build
    startCommand: |
      cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
