import React, { useState } from 'react';
import { useSoc } from '../context/SocContext.js';
import { SeverityBadge } from '../components/common/Badges.js';
import { BellRing, Check, CheckCircle2, ShieldCheck, Filter } from 'lucide-react';

export const AlertsPage: React.FC = () => {
  const { alerts, acknowledgeAlert, resolveAlert } = useSoc();
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [severityFilter, setSeverityFilter] = useState('ALL');

  const filtered = alerts.filter((a) => {
    const matchesStatus = statusFilter === 'ALL' || a.status === statusFilter;
    const matchesSev = severityFilter === 'ALL' || a.severity === severityFilter;
    return matchesStatus && matchesSev;
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-100 flex items-center gap-2">
            <BellRing className="w-6 h-6 text-orange-400" />
            Security Alert Queue & Triage
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Prioritized automotive alarms generated by the threat detection engine
          </p>
        </div>
      </div>

      <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800 flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-4 text-xs">
          <div className="flex items-center gap-2">
            <Filter className="w-3.5 h-3.5 text-slate-400" />
            <span className="text-slate-400">Status:</span>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="bg-slate-800 border border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-200 focus:outline-none"
            >
              <option value="ALL">All Alerts</option>
              <option value="ACTIVE">ACTIVE</option>
              <option value="ACKNOWLEDGED">ACKNOWLEDGED</option>
              <option value="RESOLVED">RESOLVED</option>
            </select>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-slate-400">Severity:</span>
            <select
              value={severityFilter}
              onChange={(e) => setSeverityFilter(e.target.value)}
              className="bg-slate-800 border border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-200 focus:outline-none"
            >
              <option value="ALL">All Severities</option>
              <option value="CRITICAL">CRITICAL</option>
              <option value="HIGH">HIGH</option>
              <option value="MEDIUM">MEDIUM</option>
            </select>
          </div>
        </div>

        <div className="text-xs font-mono text-slate-400">
          Showing: <strong className="text-cyan-400">{filtered.length}</strong> alerts
        </div>
      </div>

      <div className="rounded-2xl bg-slate-900/60 border border-slate-800 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-slate-300">
            <thead className="bg-slate-950/80 uppercase font-mono text-[11px] text-slate-400 border-b border-slate-800">
              <tr>
                <th className="px-5 py-3">Alert ID</th>
                <th className="px-5 py-3">Timestamp</th>
                <th className="px-5 py-3">Vehicle</th>
                <th className="px-5 py-3">ECU ID</th>
                <th className="px-5 py-3">Threat Type</th>
                <th className="px-5 py-3">Severity</th>
                <th className="px-5 py-3">Description</th>
                <th className="px-5 py-3">Status</th>
                <th className="px-5 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60">
              {filtered.length === 0 ? (
                <tr>
                  <td colSpan={9} className="px-5 py-12 text-center text-slate-500">
                    No alerts in this view.
                  </td>
                </tr>
              ) : (
                filtered.map((alt) => (
                  <tr key={alt.id} className="hover:bg-slate-800/30 transition">
                    <td className="px-5 py-3.5 font-mono font-bold text-slate-300">{alt.id}</td>
                    <td className="px-5 py-3.5 font-mono text-slate-500">
                      {new Date(alt.timestamp).toLocaleTimeString()}
                    </td>
                    <td className="px-5 py-3.5 font-mono font-semibold text-cyan-400">{alt.vehicle_id}</td>
                    <td className="px-5 py-3.5 font-mono text-slate-400">{alt.ecu_id}</td>
                    <td className="px-5 py-3.5 font-semibold text-slate-200">{alt.threat_type}</td>
                    <td className="px-5 py-3.5">
                      <SeverityBadge severity={alt.severity} />
                    </td>
                    <td className="px-5 py-3.5 text-slate-400 max-w-xs truncate">{alt.description}</td>
                    <td className="px-5 py-3.5">
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] font-bold font-mono ${
                          alt.status === 'ACTIVE'
                            ? 'bg-rose-950/80 text-rose-400 border border-rose-500/40'
                            : alt.status === 'ACKNOWLEDGED'
                            ? 'bg-amber-950/80 text-amber-400 border border-amber-500/40'
                            : 'bg-emerald-950/80 text-emerald-400 border border-emerald-500/40'
                        }`}
                      >
                        {alt.status}
                      </span>
                    </td>
                    <td className="px-5 py-3.5 text-right space-x-2">
                      {alt.status === 'ACTIVE' && (
                        <button
                          onClick={() => acknowledgeAlert(alt.id)}
                          className="px-2.5 py-1 rounded bg-amber-600/80 hover:bg-amber-600 text-white font-medium text-[11px] transition shadow-sm"
                        >
                          Acknowledge
                        </button>
                      )}
                      {alt.status !== 'RESOLVED' && (
                        <button
                          onClick={() => resolveAlert(alt.id)}
                          className="px-2.5 py-1 rounded bg-emerald-600/80 hover:bg-emerald-600 text-white font-medium text-[11px] transition shadow-sm"
                        >
                          Resolve
                        </button>
                      )}
                      {alt.status === 'RESOLVED' && (
                        <span className="text-slate-500 text-[11px] italic font-mono">Closed</span>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
